/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coPilotUI;

import java.awt.Component;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import utopiacopilot.UtopiaCoPilot;

/**
 *
 * @author paul
 */
public class coPilotMainUI extends javax.swing.JFrame {

    /**
     * Creates new form coPilotMainUI
     */
    public coPilotMainUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainTab = new javax.swing.JTabbedPane();
        irc = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        self1 = new javax.swing.JComboBox();
        selfButton1 = new javax.swing.JToggleButton();
        self2 = new javax.swing.JComboBox();
        selfButton2 = new javax.swing.JToggleButton();
        self3 = new javax.swing.JComboBox();
        selfButton3 = new javax.swing.JToggleButton();
        self4 = new javax.swing.JComboBox();
        selfButton4 = new javax.swing.JToggleButton();
        self5 = new javax.swing.JComboBox();
        selfButton5 = new javax.swing.JToggleButton();
        self6 = new javax.swing.JComboBox();
        selfButton6 = new javax.swing.JToggleButton();
        self7 = new javax.swing.JComboBox();
        selfButton7 = new javax.swing.JToggleButton();
        self8 = new javax.swing.JComboBox();
        selfButton8 = new javax.swing.JToggleButton();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Utopia CoPilot");

        mainTab.addTab("    IRC    ", irc);

        List file = null;
        try {
            file = readFile(new File("").getAbsolutePath()+"/Data/SelfSpells");
            self1.setModel(new javax.swing.DefaultComboBoxModel(file.toArray(new String[file.size()])));
        } catch (IOException ex) {
            Logger.getLogger(coPilotMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        self1.setActionCommand("");

        selfButton1.setText("Auto-Renew");
        selfButton1.setActionCommand("");

        self2.setModel(new javax.swing.DefaultComboBoxModel(file.toArray(new String[file.size()])));
        self2.setActionCommand("");

        selfButton2.setText("Auto-Renew");
        selfButton2.setActionCommand("");

        self3.setModel(new javax.swing.DefaultComboBoxModel(file.toArray(new String[file.size()])));
        self3.setActionCommand("");

        selfButton3.setText("Auto-Renew");
        selfButton3.setActionCommand("");

        self4.setModel(new javax.swing.DefaultComboBoxModel(file.toArray(new String[file.size()])));
        self4.setActionCommand("");

        selfButton4.setText("Auto-Renew");
        selfButton4.setActionCommand("");

        self5.setModel(new javax.swing.DefaultComboBoxModel(file.toArray(new String[file.size()])));
        self5.setActionCommand("");

        selfButton5.setText("Auto-Renew");
        selfButton5.setActionCommand("");

        self6.setModel(new javax.swing.DefaultComboBoxModel(file.toArray(new String[file.size()])));
        self6.setActionCommand("");

        selfButton6.setText("Auto-Renew");
        selfButton6.setActionCommand("");

        self7.setModel(new javax.swing.DefaultComboBoxModel(file.toArray(new String[file.size()])));
        self7.setActionCommand("");

        selfButton7.setText("Auto-Renew");
        selfButton7.setActionCommand("");

        self8.setModel(new javax.swing.DefaultComboBoxModel(file.toArray(new String[file.size()])));
        self8.setActionCommand("");
        setSelfSelected();

        selfButton8.setText("Auto-Renew");
        selfButton8.setActionCommand("");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(self3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selfButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(self4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selfButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(self5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selfButton5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(self6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selfButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(self7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selfButton7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(self8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selfButton8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(submit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(self1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(self2, 0, 704, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selfButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selfButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(self1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selfButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(self2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selfButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(self3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selfButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(self4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selfButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(self5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selfButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(self6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selfButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(self7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selfButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(self8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selfButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit)
                .addContainerGap())
        );

        mainTab.addTab("SelfSpells", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        TreeMap<String,String> map = new TreeMap<>();
        if (selfButton1.isSelected()) { map.put(self1.getSelectedItem().toString(),String.valueOf(selfButton1.isSelected())); }
        if (selfButton2.isSelected()) { map.put(self2.getSelectedItem().toString(),String.valueOf(selfButton2.isSelected())); }
        if (selfButton3.isSelected()) { map.put(self3.getSelectedItem().toString(),String.valueOf(selfButton3.isSelected())); }
        if (selfButton4.isSelected()) { map.put(self4.getSelectedItem().toString(),String.valueOf(selfButton4.isSelected())); }
        if (selfButton5.isSelected()) { map.put(self5.getSelectedItem().toString(),String.valueOf(selfButton5.isSelected())); }
        if (selfButton6.isSelected()) { map.put(self6.getSelectedItem().toString(),String.valueOf(selfButton6.isSelected())); }
        if (selfButton7.isSelected()) { map.put(self7.getSelectedItem().toString(),String.valueOf(selfButton7.isSelected())); }       
        if (selfButton8.isSelected()) { map.put(self8.getSelectedItem().toString(),String.valueOf(selfButton8.isSelected())); }
        String currentDir = new File("").getAbsolutePath();
        File selfSpells = new File(currentDir+"/Data/selfspells.properties");
        FileWriter selfSpellsWriter;
        try {
            selfSpellsWriter = new FileWriter(selfSpells, false);
        for(String key:map.keySet()){
            selfSpellsWriter.write(key +" = "+map.get(key)+"\n");
        }
        selfSpellsWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(coPilotMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void launchUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coPilotMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coPilotMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coPilotMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coPilotMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coPilotMainUI().setVisible(true);
                UtopiaCoPilot launcher = new UtopiaCoPilot();
                launcher.addScripter();
            }
        });
    }
    
    public static void main(String[] args) {
        launchUI();
        
        //irc.addTab("Test", launch);
    }
    
    void setSelfSelected() {
        List<String> self = null;
        try {
            self = readFile(new File("").getAbsolutePath()+"/Data/selfspells.properties");
        } catch (IOException ex) {
            Logger.getLogger(coPilotMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        int i = 0;
        for (String line:self){
            i++;
            if (i==1) { self1.setSelectedItem(line.split("=")[0].trim()); selfButton1.setSelected(true); }
            if (i==2) { self2.setSelectedItem(line.split("=")[0].trim()); selfButton2.setSelected(true); }
            if (i==3) { self3.setSelectedItem(line.split("=")[0].trim()); selfButton3.setSelected(true); }
            if (i==4) { self4.setSelectedItem(line.split("=")[0].trim()); selfButton4.setSelected(true); }
            if (i==5) { self5.setSelectedItem(line.split("=")[0].trim()); selfButton5.setSelected(true); }
            if (i==6) { self6.setSelectedItem(line.split("=")[0].trim()); selfButton6.setSelected(true); }
            if (i==7) { self7.setSelectedItem(line.split("=")[0].trim()); selfButton7.setSelected(true); }
            if (i==8) { self8.setSelectedItem(line.split("=")[0].trim()); selfButton8.setSelected(true); }
        }
    }
    
    List<String> readFile(String fileName) throws IOException {
        Path path = Paths.get(fileName);
        return Files.readAllLines(path,StandardCharsets.UTF_8);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane irc;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JTabbedPane mainTab;
    public static javax.swing.JComboBox self1;
    public static javax.swing.JComboBox self2;
    public static javax.swing.JComboBox self3;
    public static javax.swing.JComboBox self4;
    public static javax.swing.JComboBox self5;
    public static javax.swing.JComboBox self6;
    public static javax.swing.JComboBox self7;
    public static javax.swing.JComboBox self8;
    public static javax.swing.JToggleButton selfButton1;
    public static javax.swing.JToggleButton selfButton2;
    public static javax.swing.JToggleButton selfButton3;
    public static javax.swing.JToggleButton selfButton4;
    public static javax.swing.JToggleButton selfButton5;
    public static javax.swing.JToggleButton selfButton6;
    public static javax.swing.JToggleButton selfButton7;
    public static javax.swing.JToggleButton selfButton8;
    public static javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
