/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coPilotUI;

import java.awt.Component;
import javax.swing.JTextField;
import utopiacopilot.UtopiaCoPilot;

/**
 *
 * @author paul
 */
public class ircChannelUI extends javax.swing.JPanel {

    /**
     * Creates new form ircChannelUI
     */
    public ircChannelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        channelText = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        channelMessage = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        channelText.setName(UtopiaCoPilot.channelName);
        channelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channelTextActionPerformed(evt);
            }
        });
        UtopiaCoPilot.sendTextFieldsList.put(UtopiaCoPilot.channelName,channelText);

        sendButton.setText("Send");
        sendButton.setName(UtopiaCoPilot.channelName);
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        UtopiaCoPilot.sendButtons.put(UtopiaCoPilot.channelName,sendButton);

        channelMessage.setEditable(false);
        channelMessage.setColumns(20);
        channelMessage.setLineWrap(true);
        channelMessage.setRows(5);
        channelMessage.setWrapStyleWord(true);
        channelMessage.setName(UtopiaCoPilot.channelName);
        UtopiaCoPilot.channelList.put(UtopiaCoPilot.channelName,channelMessage);
        jScrollPane3.setViewportView(channelMessage);

        jList1.setName(UtopiaCoPilot.channelName);
        UtopiaCoPilot.nickLists.put(UtopiaCoPilot.channelName,jList1);
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(channelText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(channelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String selectedName = coPilotMainUI.irc.getSelectedComponent().getName();
        JTextField selected=UtopiaCoPilot.sendTextFieldsList.get(selectedName);
        UtopiaCoPilot.Speak(selected.getText(),selected.getName());
        selected.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void channelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channelTextActionPerformed
        String selectedName = coPilotMainUI.irc.getSelectedComponent().getName();
        JTextField selected=UtopiaCoPilot.sendTextFieldsList.get(selectedName);
        UtopiaCoPilot.Speak(selected.getText(),selected.getName());
        selected.setText("");
    }//GEN-LAST:event_channelTextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea channelMessage;
    public static javax.swing.JTextField channelText;
    public static javax.swing.JList jList1;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
