/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coPilotUI;

import javax.swing.JTextField;
import utopiacopilot.UtopiaCoPilot;

/**
 *
 * @author paul
 */
public class IRCServerUI extends javax.swing.JPanel {

    /**
     * Creates new form IRCServerUI
     */
    public IRCServerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        serverSend = new javax.swing.JTextField();
        serverSendButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        serverText = new javax.swing.JTextArea();

        UtopiaCoPilot.sendTextFieldsList.put(UtopiaCoPilot.serverName,serverSend);
        serverSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverSendActionPerformed(evt);
            }
        });

        serverSendButton.setText("Send");
        serverSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverSendButtonActionPerformed(evt);
            }
        });
        UtopiaCoPilot.sendButtons.put(UtopiaCoPilot.serverName,serverSendButton);

        serverText.setEditable(false);
        serverText.setColumns(20);
        serverText.setLineWrap(true);
        serverText.setRows(5);
        serverText.setWrapStyleWord(true);
        UtopiaCoPilot.channelList.put(UtopiaCoPilot.serverName,serverText);
        jScrollPane3.setViewportView(serverText);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(serverSend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverSendButton))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverSendButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serverSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverSendButtonActionPerformed
        String selectedName = coPilotMainUI.irc.getSelectedComponent().getName();
        JTextField selected=UtopiaCoPilot.sendTextFieldsList.get(selectedName);
        UtopiaCoPilot.Speak(selected.getText(),selected.getName());
        selected.setText("");
    }//GEN-LAST:event_serverSendButtonActionPerformed

    private void serverSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverSendActionPerformed
        String selectedName = coPilotMainUI.irc.getSelectedComponent().getName();
        JTextField selected=UtopiaCoPilot.sendTextFieldsList.get(selectedName);
        UtopiaCoPilot.Speak(selected.getText(),selected.getName());
        selected.setText("");
    }//GEN-LAST:event_serverSendActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextField serverSend;
    public static javax.swing.JButton serverSendButton;
    public static javax.swing.JTextArea serverText;
    // End of variables declaration//GEN-END:variables
}
